export default {
  login: "anand-nakat",
  id: 60821265,
  node_id: "MDQ6VXNlcjYwODIxMjY1",
  avatar_url: "https://avatars0.githubusercontent.com/u/60821265?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/anand-nakat",
  html_url: "https://github.com/anand-nakat",
  followers_url: "https://api.github.com/users/anand-nakat/followers",
  following_url:
    "https://api.github.com/users/anand-nakat/following{/other_user}",
  gists_url: "https://api.github.com/users/anand-nakat/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/anand-nakat/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/anand-nakat/subscriptions",
  organizations_url: "https://api.github.com/users/anand-nakat/orgs",
  repos_url: "https://api.github.com/users/anand-nakat/repos",
  events_url: "https://api.github.com/users/anand-nakat/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/anand-nakat/received_events",
  type: "User",
  site_admin: false,
  name: "Anand Nakat",
  company: null,
  blog: "https://anand-nakat.netlify.app/",
  location: "Pune",
  email: null,
  hireable: null,
  bio: "React Developer || Full Stack Enthusiast",
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2020-02-08T16:04:04Z",
  updated_at: "2021-01-11T13:30:49Z",
};

/* export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
}; */
